### ISSUE TITLE
Increase contrast for logo in dark mode

### ISSUE THREAD

**Issue by jcbhmr** [symbola/symbola#28]
![image](https://user-images.githubusercontent.com/61068799/236398146-9433047e-2d01-40ca-baed-704b6e837946.png)

right now it's pretty much unreadbable 😕
a white or gray bg would get great!

I'm willing to open a pr ❤️ just want to make sure it wont be stuck in limbo 😅

**Comment by slikts** [comment]
Thanks for the suggestion, I've actually remade the logo and the splash image so that it fixes the contrast and just haven't updated the main branch yet.

![image](https://github.com/symbola/symbola/assets/137872/ed681697-6ab3-4851-8fed-dabc6682a7e5)
